import json
import os
import sys
import pandas as pd
from tqdm import tqdm
import logging

sys.path.append("computergym/")
import main


def create_opt(models, task_names):
    opt = main.parse_opt()
    opt.llm = None
    opt.env = None
    opt.num_episodes = 10
    opt.step = -1  # -1 means use the plan step generated by the llm
    opt.erci = 1
    opt.irci = 3
    opt.prompt_token_price = 0.03       #0.002
    opt.completion_token_price = 0.06   #0.002
    opt.sgrounding = True
    opt.headless = True

    # adding new fields to the opt object
    setattr(opt, "models", models)
    setattr(opt, "task_names", task_names)

    name = "sanity_check"
    results_dir = "/mnt/ui_copilot/results/RCI/06_28_benchmark_star_coder/"
    setattr(opt, "results_dir", results_dir)
    setattr(opt, "name", name)

    # storing all the hyper-parameters and settings in a json file
    with open("arguments.json", "w") as f:
        json.dump(vars(opt), f)

    return opt


def save_model_results(df, model, name="", path=""):
    df_model = df.loc[df["model name"] == model]
    df_model = df_model.drop("model name", axis=1)

    filename = "results_" + model + "_" + name + ".xlsx"
    os.makedirs(path, exist_ok=True)

    file_path = os.path.join(path, filename)
    if os.path.exists(file_path):
        os.remove(file_path)
    df_model.to_excel(file_path, index=False)

    filename = "results_" + model + "_" + name + ".json"
    file_path = os.path.join(path, filename)
    if os.path.exists(file_path):
        os.remove(file_path)
    df_model.to_json(file_path)


# manual AZERTY/QWERTY prevention
# print("Please press the 'A' key on your keyboard:")
# user_input = input()

# reading the models and tasks from the json files
model_filename = "model_names.json"
tasks_filename = "task_names.json"


with open(model_filename) as f:
    models = json.load(f)["model_name"]
with open(tasks_filename) as f:
    task_names = json.load(f)["task_name"]

# creating the opt object
opt = create_opt(models, task_names)

if os.path.exists("error_logs.txt"):
    os.remove("error_logs.txt")

columns = [
    "model name",
    "task_name",
    "success_rate",
    "min tokens sent",
    "max tokens sent",
    "avg tokens sent",
    "min tokens received",
    "max tokens received",
    "avg tokens received",
    "n LLM calls",
    "time",
    "estimated cost",
    "experiment folder",
]
df = pd.DataFrame(columns=columns)

budget = 100  # budget in USD
remaining_budget = budget
flag = False

# running the main loop
for model in tqdm(models, desc="Models") if not flag else []:
    print("Using model : ", model)
    opt.llm = model  # switch model
    for task_name in tqdm(task_names, desc="Tasks", leave=False) if not flag else []:
        opt.env = task_name  # switch task
        print("     Task addressed : ", opt.env, "\n")
        try:
            if remaining_budget <= 0:
                flag = True
                raise Exception("Budget exhausted")
            result = main.miniwob(opt)  # running benchmark
            # storing the latest results in the dataframe
            df.loc[len(df)] = [
                model,
                task_name,
                result["success_rate"],
                result["min_sent"],
                result["max_sent"],
                result["mean_sent"],
                result["min_received"],
                result["max_received"],
                result["mean_received"],
                result["mean_calls"],
                result["time"],
                result["cost"],
                result["experiment folder"],
            ]
            # updating the budget
            remaining_budget -= result["cost"]

        except Exception as e:
            with open("error_logs.txt", "a") as f:
                f.write("error in the task : " + task_name + " , exception : " + str(e) + "\n")

            df.loc[len(df)] = [model, task_name, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, "error"]

        save_model_results(
            df, model, opt.name, opt.results_dir
        )  # saving the results of the model in a json and excel file

logging.info("total cost : " + str(budget - remaining_budget))
